name: Deploy Terraform
on:
  workflow_dispatch:
    inputs:
      needdeploy:
        description: 'Need to push to Docker Registry?'
        required: true
        default: '(Yes)'
        type: choice
        options:
        - (Yes)
        - (No)
  pull_request:
    branches: [master]
    types: [opened, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform fmt
        working-directory: ./eks_dep
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        working-directory: ./eks_dep
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: ./eks_dep
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: ./eks_dep
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform apply force
        working-directory: ./eks_dep
        id: apply
        run: terraform apply -auto-approve -no-color
        continue-on-error: true

      - name: Terraform destroy force
        working-directory: ./eks_dep
        id: destroy
        run: terraform destroy -auto-approve -no-color
        continue-on-error: true